import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Header, Footer } from 'app/components/shared'
import './globals.css'

const poppins = Poppins({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'App Store',
	description: 'Generated by me!',
}

type LayoutProps = {
	children: React.ReactNode
}

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
